# Generated by Django 5.0.6 on 2024-07-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgerule',
            name='knowledge',
        ),
        migrations.AddField(
            model_name='knowledgerule',
            name='knowledges',
            field=models.ManyToManyField(to='recommendation.knowledge'),
        ),
    ]
