# Generated by Django 5.0.6 on 2024-07-01 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_remove_knowledgerule_knowledge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgerule',
            name='knowledges',
        ),
        migrations.RemoveField(
            model_name='knowledgerule',
            name='value',
        ),
        migrations.CreateModel(
            name='KnowledgeRuleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.knowledge')),
                ('knowledge_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='recommendation.knowledgerule')),
            ],
        ),
    ]
