# Generated by Django 5.0.6 on 2024-07-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_remove_knowledge_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='description',
        ),
    ]
