# Generated by Django 5.0.6 on 2024-07-18 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_remove_crop_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledgefuzzyvalue',
            old_name='fuzzy_value',
            new_name='x1',
        ),
        migrations.AddField(
            model_name='knowledgefuzzyvalue',
            name='knowledge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recommendation.knowledge'),
        ),
        migrations.AddField(
            model_name='knowledgefuzzyvalue',
            name='x2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgefuzzyvalue',
            name='x3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgefuzzyvalue',
            name='x4',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
