# Generated by Django 5.0.6 on 2024-07-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_rename_fuzzy_value_knowledgefuzzyvalue_x1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgefuzzyvalue',
            name='fuzzy_set_type',
            field=models.CharField(choices=[('Triangular', 'Triangular'), ('Trapezoidal', 'Trapezoidal'), ('Left Shoulder', 'Left Shoulder'), ('Right Shoulder', 'Right Shoulder')], max_length=100),
        ),
    ]
