# Generated by Django 5.0.6 on 2024-07-25 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0008_knowledge_crop_alter_knowledgefuzzyvalue_knowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgefuzzyvalue',
            name='knowledge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recommendation.knowledge'),
        ),
    ]
