# Generated by Django 5.0.6 on 2024-07-29 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0009_alter_knowledgefuzzyvalue_knowledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='crop',
        ),
    ]
