# Generated by Django 5.0.6 on 2024-07-29 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0010_remove_knowledge_crop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgefuzzyvalue',
            name='knowledge_rule',
        ),
        migrations.AddField(
            model_name='knowledgefuzzyvalue',
            name='crop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recommendation.crop'),
        ),
    ]
